### PR TITLE
Feat: Add the possibility to specify jwt content

### PR DESCRIPTION
**Pull request by Demacri**
**Overview**
This pull request includes an improvement to the AdonisJS JWT authentication package.

**Configuration Enhancements:**

Added a new content option to the jwtGuard configuration in src/define_config.ts to allow custom JWT content.

**JWT Guard Enhancements:**

Introduced a content function in JwtGuardOptions to customize the JWT payload.
Updated JwtGuard to utilize the content function during token generation.

**Added tests:**

Added a new test case in tests/guard.spec.ts to verify the custom JWT content functionality.

This pull request aims to enhance the flexibility and functionality of the AdonisJS JWT package, providing more options for customization and better alignment with user needs.

### CODE REVIEW

**Comment by MaximeMRF** [comment]
Hi @Demacri,

seems nice, I will check it soon

**Comment by MaximeMRF** [comment]
Please don't update the `it should return a token when user is authenticated` test and create another one for your feature

**Comment by Demacri** [comment]
> Please don't update the `it should return a token when user is authenticated` test and create another one for your feature

so sorry, i deleted it accidentally. Squashed and pushed new commit

**Comment by MaximeMRF** [comment]
thanks for your contribution ❤️

**Pull request merged**
